"""Phrase catalog: deterministic insult replies for the Discord 'matchbot' trigger.

This module is intentionally "dumb": constants only (no RNG, no logic).
Selection is performed in server.py using a local seeded random.Random(message.id).
"""

from __future__ import annotations

MATCHBOT_INSULTS: list[str] = [
    "You’re like the end piece of bread in a loaf: everyone touches you but no one wants you.",
    "I’d love to see things from your perspective, but I can’t get my head that far up your ass.",
    "If you were a spice, you’d be flour.",
    "You’re as useful as Anne Frank’s drum set.",
    "You’re about as useful as a screen door on a submarine.",
    "Your mom’s so old, the milk in her tits has turned to powder.",
    "I bet you put corners on your nether portals.",
    "I understand why you have four layers of paint on your face.",
    "Is that acne on your face, or battle scars from your 9-month war with the coat hanger?",
    "I thought we’d hit the bottom of the gene pool until you knocked from below.",
    "You’re the reason the gene pool needs a lifeguard.",
    "You’re so fucking stupid, I could drop you in a barrel full of tits and you’d come up sucking your own thumb.",
    "You have no personality; you’re like the color beige if beige were an absolute cunt.",
    "You look like the kind of person who enjoys it when his fingers slip while wiping.",
    "Your mother was a hamster and your father smelt of elderberries.",
    "You’re almost as appealing as warm coleslaw.",
    "You’re about as useful as a condom in a convent.",
    "It’s tough to imagine you have any insecurities, because nothing stands out about you.",
    "I know five fat people, and you’re three of them.",
    "If your eyes were any further apart, you’d be a herbivore.",
    "Your face is like the sun — looking directly at it burns my retinas.",
    "If the Catholic Church saw you, they’d start promoting abortions.",
    "You’re so full of shit, if you got an enema you could be buried in a matchbox.",
    "You’re so ugly, you’d make a train take a dirt road.",
    "You’re so ugly you’d gag a sack of assholes.",
    "You’re uglier than homemade soap.",
    "You’re the fastest piece of bacon I’ve ever seen.",
    "You’re so ugly you could be a modern art masterpiece.",
    "Your grades say “marry rich,” but your looks say “try harder.”",
    "You’re not pretty enough to be this dumb.",
    "Your grades are saying “be a stripper,” but your body is saying “study up.”",
    "The jerk store called — they’re running out of you.",
    "You’re the reason your parents aren’t happy.",
    "If you were any dumber, we’d have to water you twice a week.",
    "Your mom told you that you could become anything... and you became a disappointment.",
    "You do realize people only tolerate you.",
    "I’m jealous of people who don’t know you.",
    "This is why Mom doesn’t fucking love you.",
    "Talking to you is like charity — I’m just making my donation.",
    "Your comments are as useful as a papier-mâché bomb shelter.",
    "Your life is a joke, and no one’s laughing.",
    "I didn’t know they stacked shit that high.",
    "Put your shoes back on; I’ll do the math for you.",
    "Whoever told you to “be yourself” gave you bad advice.",
    "I’ll fuck your dad and give him the son he deserves.",
    "Those look natural. Did you put them in yourself?",
    "You have room-temperature IQ.",
    "Your face looks like something I’d draw with my left hand.",
    "You’re the human equivalent of Internet Explorer.",
    "You have a face for radio and a voice for magazines.",
    "I can’t believe you were the fastest sperm.",
    "Looks like God hit the randomize button when he made you.",
    "It’s impossible to underestimate you.",
    "Have the day you deserve.",
    "I’d call you a cunt, but you lack both the depth and the warmth.",
    "You should go fuck yourself — because no one else will.",
    "You’re so fat, when Thanos snapped his fingers you only lost weight.",
    "Does your asshole ever get jealous of the shit that comes out of your mouth?",
    "You and yourself need to get a room.",
    "You’re as useful as spam mail.",
    "I don’t actually hate you; I’m just trying to fit in with everyone else.",
    "You fucking donkey.",
    "You’re not being the person Mr. Rogers thought you could be.",
    "I don’t know who I feel worse for: your parents or your mirror.",
    "You’re made of spare parts, aren’t you?",
    "If you were a bird, you’d be a peli-can’t.",
    "You’re as useless as a suitcase without handles.",
    "That looks like Cinderella’s dress... but when she was still poor.",
    "I have neither the time nor the crayons to explain this to you.",
    "Are you a professional idiot or just a gifted amateur?",
    "If I wanted any more shit from you, I’d squeeze your head.",
    "If I throw a stick, will you go away?",
    "You weren’t just dropped as a baby — you were thrown.",
    "I would agree with you, but then we’d both be wrong.",
    "If I wanted to hear from an asshole, I’d fart.",
    "You’re not completely useless; you can always serve as a bad example.",
    "There’s a tree out there producing oxygen for you... you owe it an apology.",
    "You have the charisma of a damp rag and the appearance of a low-grade bank clerk.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "It’s almost sad watching you try to fit your entire vocabulary into one sentence.",
    "You have delusions of adequacy.",
    "I refuse to have a battle of wits with an unarmed person.",
    "You’re as sharp as a marble.",
    "You couldn’t pour water out of a boot if the instructions were on the heel.",
    "If brains were dynamite, you couldn’t blow your hat off.",
    "You’re the reason shampoo has directions.",
    "You couldn’t organize a piss-up in a brewery.",
    "It’s kind of cute how you think you’re doing a good job.",
    "Everyone who ever loved you was wrong.",
    "I hope your day is as pleasant as you are.",
    "Mirrors can’t talk. Lucky for you, they can’t laugh either.",
    "You bring everyone a lot of joy... when you leave the room.",
    "I’ve seen pride parades straighter than your jump shot.",
    "Your only chance at getting laid is crawling up a chicken’s ass and waiting.",
    "The last time I saw something like you, I flushed it.",
    "You have the personality of a speed bump.",
    "You are proof that evolution can go in reverse.",
    "Light travels faster than sound, which is why you seemed bright until you spoke.",
    "We all sprang from apes, but you didn’t spring far enough.",
    "Some drink from the fountain of knowledge; you only gargled.",
    "If I wanted a bitch, I would buy a dog.",
    "The first 40 years of childhood are always the hardest.",
    "I’d tell you to go to hell, but I don’t want to see you at work.",
    "You’re so dumb, you’d trip over a cordless phone.",
    "You’re a few fries short of a Happy Meal.",
    "Even your shadow leaves you.",
    "Your IQ is so low, it could win a limbo contest.",
    "If brains were leather, you wouldn’t have enough to saddle a flea.",
    "You’re as useless as a one-legged man in an ass-kicking contest.",
    "Earth is full. Go home.",
    "The only culture you have is bacterial.",
    "I see you’ve set aside some time to embarrass yourself in public.",
    "Everyone brings happiness to a room: I bring it when I enter, and you bring it when you leave.",
    "Brains aren’t everything. In your case, they’re nothing.",
    "Pardon me, but you’ve obviously mistaken me for someone who gives a damn.",
    "Don’t you have a terribly empty feeling... in your skull?",
    "Have you been shopping lately? They’re selling lives — you should go get one.",
    "My therapist said I was crazy. I asked for a second opinion; he said I’m ugly too.",
    "You’re so ugly, when your mom dropped you off at school she got fined for littering.",
    "You have diarrhea of the mouth and constipation of ideas.",
    "Why don’t you slip into something more comfortable... like a coma.",
    "Some babies were dropped on their heads, but you were clearly thrown at a wall.",
    "Just because you have one doesn’t mean you have to act like one.",
    "You’re so gullible, I could sell you air and you’d buy it.",
    "There’s no vaccine against stupidity.",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "You’re so clumsy, you could trip over a wireless network.",
    "If there were a contest for the most clueless person, you’d probably forget to show up.",
    "You’re as useful as a waterproof teabag.",
    "You’re not just a clown; you’re the entire circus.",
    "You’re the human equivalent of a participation trophy.",
    "If idiocy were an art form, you’d be a masterpiece.",
    "Stupidity isn’t a crime, so you’re free to go.",
    "You’ve achieved the perfect work-life balance: you’re equally incompetent at both.",
    "You’re so dumb, you got hit by a parked car.",
    "I’m not saying you’re stupid, but if there were a zombie apocalypse, you’d bring a spoon.",
    "You have the dance moves of a rubber duck on roller skates.",
    "You’re a marshmallow in a world of pineapples.",
    "You have the memory of a goldfish with amnesia.",
    "You have the wit of a snail on vacation.",
    "You have the fashion sense of a rainbow-colored banana.",
    "You’re as fierce as a cuddly teddy bear with a permanent smile.",
    "You have the strategic genius of a squirrel playing chess against a walnut.",
    "You have the hunting instincts of a vegetarian shark.",
    "Your agility is comparable to a turtle on a trampoline.",
    "You have the comedic timing of a rubber chicken on a trampoline.",
    "You have the problem-solving skills of a confused penguin in a desert.",
    "You’re a walking dictionary of gibberish and tomfoolery.",
    "You’re a maestro of nonsense, conducting chaos with finesse.",
    "Your attention span is shorter than a hummingbird on an espresso binge.",
    "You have the comedic timing of a rubber duck hosting a stand-up show.",
    "For someone who lives online, you'd think you could download a clue by now.",
    "Your builds are so bad, even IceFrog would disown you.",
    "I'm curious, what preschool did you drop out of?",
    "Out of 10, you're a -5, and that's me being generous.",
    "If unearned confidence was a crime, you'd be public enemy number one.",
    "Your gaming skills are an insult to the word 'skill'.",
    "Your Dota skills are like a placebo: nonexistent, but you still think they're working.",
    "Your manners didn't just take a backseat; they jumped out of the car and ran away.",
    "The only thing you're carrying is your team's weight, and you're not doing a great job.",
    "Your thinking is so small, it's practically quantum.",
    "If I threw a stick, you'd probably fetch the wrong one.",
    "You're a few sausages short of a barbie, aren't ya?",
    "Even the voices in your head are facepalming.",
    "It's impressive how you can talk so much and say so little.",
    "You're as useless as an ashtray on a motorbike, mate.",
    "Even silence is facepalming at what you just said.",
    "I've seen better conversations in a dial-up chatroom.",
    "Your brain has two settings: off and reboot.",
    "You know you're bad at this, right? Or has that thought not arrived yet?",
    "If being annoying was a career, you'd have a corner office.",
    "If I wanted useless information, I'd tune into your stream of consciousness.",
    "The highlight of your day is probably when you manage to tie your shoes correctly.",
    "Your ego is writing checks your skills can't cash.",
    "I'd explain it to you, but I'm all out of puppets and crayons.",
    "You warthog-faced buffoon! (Oh wait, wrong script, but it still applies.)",
    "Even a broken GPS would find a clue faster than you.",
    "Crikey, even a wombat on a bad day has more brains than you.",
    "I would say karma will get you, but it looks like it already did.",
    "If game sense was water, you'd be a desert.",
    "You must have a high ping to reality.",
    "Your farm is slower than a Crystal Maiden with broken boots.",
    "Mate, you're about as sharp as a bowling ball.",
    "I'd love to continue this thrilling discussion, but I'm going to go count the ceiling tiles instead.",
    "You know, when I said 'Be yourself,' I didn't mean continue being awful.",
    "Your feeding is so consistent, the enemy team should put you on salary.",
    "I'm jealous of all the people who haven't met you.",
    "The fact you exist is proof that cosmic jokes happen.",
    "Did you know? People like you are the reason warning labels are so detailed.",
    "I hope you take this personally, because it is personal.",
    "If ignorance was a talent, you'd be a superstar.",
    "You are proof that evolution isn't linear.",
    "You have the energy of a sloth on holiday.",
    "If being insufferable was a degree, you'd have a PhD.",
    "You're so insignificant, if you were a character in a story you'd be a footnote.",
    "You manage to be a bad influence on inanimate objects.",
    "If brains were Internet speed, you'd be on dial-up.",
    "Even Easy mode is hard mode for you, isn't it?",
    "You're running on empty, and it's not even half past arvo.",
    "If I agreed with you, we'd both be wrong.",
    "Somewhere, a performance review is being written for you, and it's just one word: Don't.",
    "Your aura must be made of garlic, because everyone just wants to stay far away.",
    "I'd ask you to think before you speak, but I'm not sure you're qualified for that kind of task.",
    "Your presence is the emotional equivalent of a Windows Vista update: disruptive and unwanted.",
    "You have an uncanny talent for making every conversation dumber just by participating.",
    "You bring the room temperature down every time you enter, and not in a good way.",
    "If being clueless were a currency, you'd be richer than Elon Musk.",
    "At this point, the fountain is safer without you—just go AFK.",
    "Your voice is a great substitute for an alarm clock – impossible to ignore and extremely annoying.",
    "You're the dictionary definition of 'no one likes you.'",
    "You could start an argument with a mirror and still lose.",
    "The only legendary thing about you is your ability to find new ways to fail.",
    "I've met goldfish with longer attention spans than you.",
    "It's not that I hate you, but I would unplug your life support to charge my phone.",
    "Your strategy is so bad, even RNG can't save you.",
    "The only thing flatter than your learning curve is the flatline of your brain activity.",
    "I guess God did give with both hands—in your case, it's two left feet and no brains.",
    "Your logic is like a screen door on a submarine.",
    "They should use you as a case study for the Dunning-Kruger effect.",
    "I'd say you’re the dumbest person alive, but I’m not convinced you're actually living up there.",
    "You know you've messed up when even your imaginary friends ghost you.",
    "You're as welcome as a redback spider in a sleeping bag.",
    "If obliviousness were a superpower, you'd be the hero of your own comic.",
    "Even a koala with heatstroke has more energy than you bring to the table.",
    "The mystery isn't that you're clueless. The mystery is that you think you're not.",
    "You missed so many last hits, I'm starting to think you have Pacifist Mode on.",
    "I thought you had a point for a moment. Turns out I just lost a brain cell listening to you.",
    "I should thank you – it's not often I meet a living cautionary tale.",
    "If I had a dollar for every smart thing you've said, I'd be broke.",
    "Even the tutorial would surrender if it had to teach you.",
    "Oh honey, you're not pretty enough to act this ugly.",
    "In the sandbox of life, you’re the cat turd.",
    "I'm not ignoring you, I'm giving you the attention you deserve – none.",
    "They say the truth hurts. Let me break some bones with honesty: you're out of your depth in a kiddie pool.",
    "You remind me of a black hole: nothing intelligent escapes from you.",
    "You have one good trait: you're consistent. Consistently awful, but hey, it's something.",
    "You know, listening to you is like taking a long road trip through nothing – no point, no scenery, just a lot of wasted time.",
    "It's almost fascinating how every time you open your mouth, we all lose brain cells.",
    "Your APM is so low, I thought you were playing turn-based.",
    "I'd tell you to get lost, but wherever you went would be worse off than here.",
    "I would call you a fuckwit, but that would imply you have the wit part.",
    "The last brain cell you had must have left out of boredom.",
    "You sometimes stumble over the truth, but you always manage to get up and walk away like nothing happened.",
    "The chance of you saying something intelligent is like finding a unicorn – I'll believe it when I see it.",
    "I’ve stepped in puddles with more depth than you.",
    "Your reaction time is measured in geological eras.",
    "You're the best at what you do, and what you do is disappoint.",
    "Your headshot count is lower than your IQ, and neither is looking good.",
    "When you die in-game, even the commentators go 'finally'.",
    "The enemy team says thank you for the donation. You were very generous this match.",
    "I envy people who haven't met you.",
    "Even Pudge would be impressed by how hard you throw.",
    "You're living proof that common sense isn't so common.",
    "Your birth certificate is an apology letter from the condom factory.",
    "If stupidity were art, you'd be the Mona Lisa.",
    "The universe is expanding, and it's probably trying to get away from you.",
    "If being oblivious was an Olympic sport, you'd win gold every time (and wonder why you're on a podium).",
    "You should wear a warning label that says 'Contents under pressure: bursts of nonsense may occur.'",
    "I admire your confidence. It's utterly misplaced, but admirable nonetheless.",
    "Your face could curdle milk.",
    "Not saying you're worthless, but even zero feels more valuable compared to you.",
    "The difference between us is that when I go away, people actually miss me.",
    "If I wanted to hear white noise, I'd put on an empty TV channel, not listen to you.",
    "Even a galah learns a few words, but you? Not a single useful thought.",
    "You could hide your own Easter eggs, given your memory.",
    "Oh dear, did you actually think that comment would make you sound smart?",
    "You must main Courier, because you're only good at delivering games to the enemy.",
    "Your map awareness is as dark as an unwarded Roshan pit.",
    "Even Tiny would call your plays small.",
    "You sometimes give off the vibe that you were raised by sandflies.",
    "I wish I could unfollow you in real life.",
    "You're about as fun as a root canal, and at least that ends with painkillers.",
    "Even Roshan takes breaks; you took a vacation mid-game.",
    "If throwing games was a sport, you'd have an Aegis of Champions for it.",
    "Even my imaginary friend finds you too immature.",
    "You have the social skills of a brick and the empathy of a cactus.",
    "The only thing you ever break is the silence, and trust me, that's a crime in itself.",
    "Everyone has the right to be stupid, but you really abuse the privilege.",
    "Your gameplay provides great comic relief—too bad we're not looking for a comedy.",
    "You're the human equivalent of clickbait: all headline, no content.",
    "Keep talking, maybe one day you'll say something intelligent by accident.",
    "I admire your courage. Most people would be afraid to show such ignorance so confidently.",
    "If cluelessness were a fragrance, you'd be a best-seller.",
    "The ocean called; it wants its depth back from your shallowness.",
    "Is your keyboard broken, or do you just play like a potato on purpose?",
    "Your birth certificate should have come with an apology and a refund.",
    "Comparing us is like comparing Einstein to an empty soda can.",
    "Your decision-making is like randoming all five heroes and hoping for the best.",
    "Even the flies avoid you, and they'll land on anything.",
    "If being annoying was an Olympic event, you'd win gold and then annoy everyone on the podium.",
    "I’m not saying I hate you, but if you were on fire and I had water, I’d drink it.",
    "You have the charm of an overflowing dumpster.",
    "I guess the screw-up fairy visited you again.",
    "Maybe gaming isn't your thing. Have you tried knitting? At least if you choke, it's on yarn.",
    "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
    "Your KDA is the scariest horror story I've ever seen.",
    "If you tried to think any harder, you'd hemorrhage.",
    "Bless your heart, you even fail with such confidence.",
    "Even a blindfolded bot would outplay you.",
    "I’m not insulting you; I’m describing you.",
    "If being oblivious was fatal, you wouldn't last a minute.",
    "Your personality is like warm beer: flat and unwanted.",
    "When I look at you, I understand why some animals eat their offspring.",
    "If ignorance were a talent show, you'd get a standing ovation.",
    "Your face is proof that evolution can hiccup.",
    "I'd sugarcoat it, but you're about as sweet as a lemon soaked in vinegar.",
    "If I wanted to hear from an arsehole, I’d fart in a mirror.",
    "Your existence is the strongest argument against cloning.",
    "You have the charisma of a wet sock left in a gumboot.",
    "Even your shadow refuses to follow you closely.",
    "I'd challenge you to a battle of wits, but it wouldn't be a fair fight since you're unarmed.",
    "Even your guardian angel facepalms when you're about to speak.",
    "By the sound of it, your head's got more echo than the Sydney Opera House.",
    "Talking to you is like reading terms and conditions: nobody wants to, and it's a waste of time.",
    "I thought by now you'd learned your lesson, but clearly the class was empty.",
    "You have the innate ability to turn a brain fart into a hurricane of nonsense.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "You're the reason the gene pool needs a filter.",
    "The difference between you and a bucket of crap is the bucket.",
    "If there’s a light at the end of your tunnel, it's probably an oncoming train.",
    "Even Techies in a teamfight contributes more than you did.",
    "Your MMR is lower than your shoe size.",
    "In the great book of stupidity, you're a bestseller.",
    "If your brain was a hard drive, I'd format it and start over.",
    "Oh sweetie, I love how you state the obvious and still get it wrong.",
    "You couldn't organize a raffle in a room full of charity volunteers.",
    "Your plays are so confusing even your guardian angel uninstalled.",
    "If there were an award for being insufferable, you'd have a trophy room.",
    "I've seen creep waves with more coordination than your ganks.",
    "The only thing you're carrying is the burden of being you.",
    "Even a cane toad has more charisma than you, mate.",
    "You must be a magical creature: half wit, half twit.",
    "You're the human equivalent of a dial-up modem – loud, painfully slow, and obsolete.",
    "When I need a reminder of what not to be, I think of you.",
    "You're as handy as a back pocket on a singlet.",
    "Your insults are as effective as a Nerf gun in a warzone.",
    "I would slap you, but that would be animal abuse.",
    "You're a right egg, and not the kind that hatches into anything useful.",
    "If stupidity were a superpower, you'd be the strongest Avenger.",
    "Even your pride is ashamed of you.",
    "You have the intellectual depth of a mud puddle.",
    "You know what? The trash gets taken out more often than you get things right.",
    "Your reaction to logic is like a vampire's to sunlight.",
    "Honestly, I'd love to see things from your perspective, but I just can't get my head that far up my own arse.",
    "Even a stopped clock is right twice a day, but you? Wow, not even close.",
    "Thank you for showing us what 0 MMR gameplay looks like.",
    "Your only chance of getting laid is lying down in a field and waiting.",
    "You know, it's almost admirable how you live in your own little world. Too bad no one else wants to visit.",
    "The lights are on, but you're not even in the suburb, let alone home.",
    "If dumb were dirt, you'd be the Great Aussie Outback.",
    "You have the emotional range of a teaspoon, and even that might be overstating it.",
    "You're the reason even your echo avoids repeating you.",
    "You know you've really hit rock bottom when even the bots are typing 'gg' when you log in.",
    "You're as pleasant as a rash in summer.",
    "Your ideas are so original, they were just rejected by the dumpster.",
    "I can explain it to you, but I can't understand it for you.",
    "You know that feeling when you realize you forgot something important? That's me trying to find any value in what you say.",
    "Even Crystal Maiden would outrun your farm.",
    "If bullshit was currency, you'd be a billionaire.",
    "Your smile is proof that not everyone looks better when they smile.",
    "The ocean called; they're running out of shrimp... oh wait, wrong insult. Still, nobody likes you.",
    "Your presence in the game is about as useful as lag.",
    "If you were any slower, you'd be going backward.",
    "Your brain is like Bigfoot: people claim it exists, but no one has actually seen proof.",
    "You have the wit of a traffic cone.",
    "It's ironic that you have such a big mouth, considering how small your mind is.",
    "If unearned confidence were electricity, you could power all of Australia for a week.",
    "You're a walking argument against the concept of intelligent life on Earth.",
    "Your plays are as tragic as a 60-minute game lost to a courier snipe.",
    "If ignorance were a deadly disease, you'd be extinct.",
    "I admire your confidence. It's utterly misplaced, but hey, it's confidence.",
    "I would like to thank you for showing us what rock bottom truly looks like.",
    "You have the innate ability to bring a knife to a gunfight, metaphorically speaking.",
    "If you were on the last brain cell on Earth, I'd prefer extinction.",
    "By all means, let's keep this up. I haven't had a headache all day.",
    "You're the reason Survivor would vote people off the island on day one.",
    "Oh, I'm sorry, was the middle of my sentence interrupting the beginning of yours?",
    "Even a drop bear wouldn't bite you; it has standards.",
    "Your pride is bigger than your skill, which is saying something because your skill is microscopic.",
    "If being wrong were an Olympic event, you'd be a national hero.",
    "You could trip over a wireless connection.",
    "Your skill ceiling is a basement.",
    "If being a fool is a work of art, you’re a masterpiece.",
]

__all__ = ["MATCHBOT_INSULTS"]
