"""Phrase catalog: deterministic insult replies for the Discord 'matchbot' trigger.

This module is intentionally "dumb": constants only (no RNG, no logic).
Selection is performed in server.py using a local seeded random.Random(message.id).
"""

from __future__ import annotations

MATCHBOT_INSULTS: list[str] = [
    "You’re like the end piece of bread in a loaf: everyone touches you but no one wants you.",
    "I’d love to see things from your perspective, but I can’t get my head that far up your ass.",
    "If you were a spice, you’d be flour.",
    "You’re as useful as Anne Frank’s drum set.",
    "You’re about as useful as a screen door on a submarine.",
    "Your mom’s so old, the milk in her tits has turned to powder.",
    "I bet you put corners on your nether portals.",
    "I understand why you have four layers of paint on your face.",
    "Is that acne on your face, or battle scars from your 9-month war with the coat hanger?",
    "I thought we’d hit the bottom of the gene pool until you knocked from below.",
    "You’re the reason the gene pool needs a lifeguard.",
    "You’re so fucking stupid, I could drop you in a barrel full of tits and you’d come up sucking your own thumb.",
    "You have no personality; you’re like the color beige if beige were an absolute cunt.",
    "You look like the kind of person who enjoys it when his fingers slip while wiping.",
    "Your mother was a hamster and your father smelt of elderberries.",
    "You’re almost as appealing as warm coleslaw.",
    "You’re about as useful as a condom in a convent.",
    "It’s tough to imagine you have any insecurities, because nothing stands out about you.",
    "I know five fat people, and you’re three of them.",
    "If your eyes were any further apart, you’d be a herbivore.",
    "Your face is like the sun — looking directly at it burns my retinas.",
    "If the Catholic Church saw you, they’d start promoting abortions.",
    "You’re so full of shit, if you got an enema you could be buried in a matchbox.",
    "You’re so ugly, you’d make a train take a dirt road.",
    "You’re so ugly you’d gag a sack of assholes.",
    "You’re uglier than homemade soap.",
    "You’re the fastest piece of bacon I’ve ever seen.",
    "You’re so ugly you could be a modern art masterpiece.",
    "Your grades say “marry rich,” but your looks say “try harder.”",
    "You’re not pretty enough to be this dumb.",
    "Your grades are saying “be a stripper,” but your body is saying “study up.”",
    "The jerk store called — they’re running out of you.",
    "You’re the reason your parents aren’t happy.",
    "If you were any dumber, we’d have to water you twice a week.",
    "Your mom told you that you could become anything... and you became a disappointment.",
    "You do realize people only tolerate you.",
    "I’m jealous of people who don’t know you.",
    "This is why Mom doesn’t fucking love you.",
    "Talking to you is like charity — I’m just making my donation.",
    "Your comments are as useful as a papier-mâché bomb shelter.",
    "Your life is a joke, and no one’s laughing.",
    "I didn’t know they stacked shit that high.",
    "Put your shoes back on; I’ll do the math for you.",
    "Whoever told you to “be yourself” gave you bad advice.",
    "I’ll fuck your dad and give him the son he deserves.",
    "Those look natural. Did you put them in yourself?",
    "You have room-temperature IQ.",
    "Your face looks like something I’d draw with my left hand.",
    "You’re the human equivalent of Internet Explorer.",
    "You have a face for radio and a voice for magazines.",
    "I can’t believe you were the fastest sperm.",
    "Looks like God hit the randomize button when he made you.",
    "It’s impossible to underestimate you.",
    "Have the day you deserve.",
    "I’d call you a cunt, but you lack both the depth and the warmth.",
    "You should go fuck yourself — because no one else will.",
    "You’re so fat, when Thanos snapped his fingers you only lost weight.",
    "Does your asshole ever get jealous of the shit that comes out of your mouth?",
    "You and yourself need to get a room.",
    "You’re as useful as spam mail.",
    "I don’t actually hate you; I’m just trying to fit in with everyone else.",
    "You fucking donkey.",
    "You’re not being the person Mr. Rogers thought you could be.",
    "I don’t know who I feel worse for: your parents or your mirror.",
    "You’re made of spare parts, aren’t you?",
    "If you were a bird, you’d be a peli-can’t.",
    "You’re as useless as a suitcase without handles.",
    "That looks like Cinderella’s dress... but when she was still poor.",
    "I have neither the time nor the crayons to explain this to you.",
    "Are you a professional idiot or just a gifted amateur?",
    "If I wanted any more shit from you, I’d squeeze your head.",
    "If I throw a stick, will you go away?",
    "You weren’t just dropped as a baby — you were thrown.",
    "I would agree with you, but then we’d both be wrong.",
    "If I wanted to hear from an asshole, I’d fart.",
    "You’re not completely useless; you can always serve as a bad example.",
    "There’s a tree out there producing oxygen for you... you owe it an apology.",
    "You have the charisma of a damp rag and the appearance of a low-grade bank clerk.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "It’s almost sad watching you try to fit your entire vocabulary into one sentence.",
    "You have delusions of adequacy.",
    "I refuse to have a battle of wits with an unarmed person.",
    "You’re as sharp as a marble.",
    "You couldn’t pour water out of a boot if the instructions were on the heel.",
    "If brains were dynamite, you couldn’t blow your hat off.",
    "You’re the reason shampoo has directions.",
    "You couldn’t organize a piss-up in a brewery.",
    "It’s kind of cute how you think you’re doing a good job.",
    "Everyone who ever loved you was wrong.",
    "I hope your day is as pleasant as you are.",
    "Mirrors can’t talk. Lucky for you, they can’t laugh either.",
    "You bring everyone a lot of joy... when you leave the room.",
    "I’ve seen pride parades straighter than your jump shot.",
    "Your only chance at getting laid is crawling up a chicken’s ass and waiting.",
    "The last time I saw something like you, I flushed it.",
    "You have the personality of a speed bump.",
    "You are proof that evolution can go in reverse.",
    "Light travels faster than sound, which is why you seemed bright until you spoke.",
    "We all sprang from apes, but you didn’t spring far enough.",
    "Some drink from the fountain of knowledge; you only gargled.",
    "If I wanted a bitch, I would buy a dog.",
    "The first 40 years of childhood are always the hardest.",
    "I’d tell you to go to hell, but I don’t want to see you at work.",
    "You’re so dumb, you’d trip over a cordless phone.",
    "You’re a few fries short of a Happy Meal.",
    "Even your shadow leaves you.",
    "Your IQ is so low, it could win a limbo contest.",
    "If brains were leather, you wouldn’t have enough to saddle a flea.",
    "You’re as useless as a one-legged man in an ass-kicking contest.",
    "Earth is full. Go home.",
    "The only culture you have is bacterial.",
    "I see you’ve set aside some time to embarrass yourself in public.",
    "Everyone brings happiness to a room: I bring it when I enter, and you bring it when you leave.",
    "Brains aren’t everything. In your case, they’re nothing.",
    "Pardon me, but you’ve obviously mistaken me for someone who gives a damn.",
    "Don’t you have a terribly empty feeling... in your skull?",
    "Have you been shopping lately? They’re selling lives — you should go get one.",
    "My therapist said I was crazy. I asked for a second opinion; he said I’m ugly too.",
    "You’re so ugly, when your mom dropped you off at school she got fined for littering.",
    "You have diarrhea of the mouth and constipation of ideas.",
    "Why don’t you slip into something more comfortable... like a coma.",
    "Some babies were dropped on their heads, but you were clearly thrown at a wall.",
    "Just because you have one doesn’t mean you have to act like one.",
    "You’re so gullible, I could sell you air and you’d buy it.",
    "There’s no vaccine against stupidity.",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "You’re so clumsy, you could trip over a wireless network.",
    "If there were a contest for the most clueless person, you’d probably forget to show up.",
    "You’re as useful as a waterproof teabag.",
    "You’re not just a clown; you’re the entire circus.",
    "You’re the human equivalent of a participation trophy.",
    "If idiocy were an art form, you’d be a masterpiece.",
    "Stupidity isn’t a crime, so you’re free to go.",
    "You’ve achieved the perfect work-life balance: you’re equally incompetent at both.",
    "You’re so dumb, you got hit by a parked car.",
    "I’m not saying you’re stupid, but if there were a zombie apocalypse, you’d bring a spoon.",
    "You have the dance moves of a rubber duck on roller skates.",
    "You’re a marshmallow in a world of pineapples.",
    "You have the memory of a goldfish with amnesia.",
    "You have the wit of a snail on vacation.",
    "You have the fashion sense of a rainbow-colored banana.",
    "You’re as fierce as a cuddly teddy bear with a permanent smile.",
    "You have the strategic genius of a squirrel playing chess against a walnut.",
    "You have the hunting instincts of a vegetarian shark.",
    "Your agility is comparable to a turtle on a trampoline.",
    "You have the comedic timing of a rubber chicken on a trampoline.",
    "You have the problem-solving skills of a confused penguin in a desert.",
    "You’re a walking dictionary of gibberish and tomfoolery.",
    "You’re a maestro of nonsense, conducting chaos with finesse.",
    "Your attention span is shorter than a hummingbird on an espresso binge.",
    "You have the comedic timing of a rubber duck hosting a stand-up show."
]

__all__ = ["MATCHBOT_INSULTS"]
