# feedback/catalog/titles.py
# Deterministic per-IMP title phrases for match performance summaries
# Notes:
# - Pure lookup table: one line per integer bucket and outcome.
# - Buckets: -51..+51 plus blanket buckets -52 (≤ -52) and +52 (≥ +52).
# - Values are short phrases intended to follow a nickname in the embed.

TITLE_BY_IMP = {
    -52: {"win": "survived the win despite being a net liability", "loss": "actively accelerated the loss"},
    -51: {"win": "was dragged to victory kicking and screaming", "loss": "turned a winnable game into a collapse"},
    -50: {"win": "won despite repeated game-losing mistakes", "loss": "lost the game almost on their own"},
    -49: {"win": "won while doing the enemy team favors", "loss": "was the enemy’s best asset"},
    -48: {"win": "won despite playing against their own team", "loss": "made the loss inevitable"},
    -47: {"win": "won while consistently on the wrong side of fights", "loss": "consistently fed momentum away"},
    -46: {"win": "won despite constant negative pressure", "loss": "applied pressure exclusively to their own team"},
    -45: {"win": "won while hemorrhaging advantage", "loss": "bled the game dry"},
    -44: {"win": "won while undoing progress", "loss": "undid progress every time it appeared"},
    -43: {"win": "won despite repeated costly errors", "loss": "converted errors directly into loss"},
    -42: {"win": "won while losing every important moment", "loss": "lost every moment that mattered"},
    -41: {"win": "won despite falling behind and staying there", "loss": "fell behind and took the game with them"},
    -40: {"win": "won while acting as the wrong win condition", "loss": "was a win condition for the enemy"},
    -39: {"win": "won despite never stabilising", "loss": "never stabilised the game"},
    -38: {"win": "won while giving away control", "loss": "handed control to the enemy"},
    -37: {"win": "won while teammates compensated heavily", "loss": "forced teammates into constant recovery mode"},
    -36: {"win": "won despite leaking advantage nonstop", "loss": "leaked advantage relentlessly"},
    -35: {"win": "won while involved in everything but value", "loss": "was everywhere except the solution"},
    -34: {"win": "won while opening the map for the enemy", "loss": "opened the map for the enemy"},
    -33: {"win": "won while gifting opportunities", "loss": "gifted opportunities all game"},
    -32: {"win": "won while ignoring what the game required", "loss": "ignored what the game required"},
    -31: {"win": "won despite effort producing no leverage", "loss": "produced effort without leverage"},
    -30: {"win": "won while permanently behind the tempo", "loss": "fell behind the tempo and stayed there"},
    -29: {"win": "won while committing to losing ideas", "loss": "committed to losing ideas"},
    -28: {"win": "won while trading value downhill", "loss": "traded value downhill"},
    -27: {"win": "won while missing the win condition", "loss": "missed the win condition entirely"},
    -26: {"win": "won while turning manageable into messy", "loss": "turned manageable situations into losses"},
    -25: {"win": "won despite consistently bad trades", "loss": "consistently lost trades"},
    -24: {"win": "won while creating openings for the enemy", "loss": "created openings the enemy exploited"},
    -23: {"win": "won while ceding control", "loss": "ceded control repeatedly"},
    -22: {"win": "won despite losing key moments", "loss": "lost most key moments"},
    -21: {"win": "won while negatives outweighed positives", "loss": "negatives outweighed positives"},
    -20: {"win": "won while being part of the problem", "loss": "was part of the problem"},
    -19: {"win": "won despite failing to steady the game", "loss": "failed to steady the game"},
    -18: {"win": "won despite missed chances", "loss": "missed too many chances"},
    -17: {"win": "won with activity but little impact", "loss": "had activity without impact"},
    -16: {"win": "won while late to matter", "loss": "was late to every important moment"},
    -15: {"win": "won while giving away more than gained", "loss": "gave away more than they gained"},
    -14: {"win": "won despite sloppy execution", "loss": "execution cost the team"},
    -13: {"win": "won with inconsistent usefulness", "loss": "was inconsistently useful"},
    -12: {"win": "won with limited influence", "loss": "had limited influence"},
    -11: {"win": "won while shaping very little", "loss": "shaped very little"},
    -10: {"win": "won while quietly dragging momentum down", "loss": "slowly dragged momentum down"},
    -9: {"win": "won despite just enough mistakes to matter", "loss": "made just enough mistakes to matter"},
    -8: {"win": "won without helping much", "loss": "didn’t help much"},
    -7: {"win": "won with pressure that never paid off", "loss": "applied pressure without payoff"},
    -6: {"win": "won with more drag than damage", "loss": "added drag more than damage"},
    -5: {"win": "won just under neutral", "loss": "played just under neutral"},
    -4: {"win": "won despite small avoidable costs", "loss": "paid small avoidable costs"},
    -3: {"win": "won with a quiet, uneven game", "loss": "had a quiet, uneven game"},
    -2: {"win": "won with almost no swing", "loss": "had almost no swing"},
    -1: {"win": "won while barely registering", "loss": "barely registered"},
    0: {"win": "won with a neutral footprint", "loss": "had a neutral impact in a losing game"},
    1: {"win": "nudged the game in the right direction", "loss": "nudged the game, but not enough"},
    2: {"win": "provided small, useful contributions", "loss": "provided small help in a losing effort"},
    3: {"win": "added more than they took", "loss": "added some value, lost anyway"},
    4: {"win": "played a quietly helpful game", "loss": "played a helpful but insufficient game"},
    5: {"win": "contributed modest value over time", "loss": "contributed modest value in defeat"},
    6: {"win": "started converting actions into value", "loss": "converted some value in a loss"},
    7: {"win": "made a few plays that mattered", "loss": "made plays that didn’t swing it"},
    8: {"win": "was reliably useful", "loss": "was reliable in a losing effort"},
    9: {"win": "pulled their weight and then some", "loss": "pulled their weight, lacked support"},
    10: {"win": "made consistently winning decisions", "loss": "made good decisions in a loss"},
    11: {"win": "showed up when it mattered", "loss": "showed up, but couldn’t carry"},
    12: {"win": "made the game easier for their team", "loss": "made it easier, still lost"},
    13: {"win": "regularly improved the situation", "loss": "played well in a losing game"},
    14: {"win": "turned actions into advantage", "loss": "created advantage without a win"},
    15: {"win": "delivered clear, positive impact", "loss": "delivered impact in defeat"},
    16: {"win": "created more advantage than they gave up", "loss": "created advantage that wasn’t enough"},
    17: {"win": "pushed the game forward consistently", "loss": "pushed forward in a losing fight"},
    18: {"win": "forced reactions from the enemy", "loss": "forced reactions but no collapse"},
    19: {"win": "shaped key moments decisively", "loss": "shaped moments in a loss"},
    20: {"win": "kept the team winning-capable", "loss": "kept the team alive but lost"},
    21: {"win": "repeatedly influenced the game’s direction", "loss": "repeatedly influenced a losing game"},
    22: {"win": "clearly mattered throughout the match", "loss": "clearly mattered, lacked backup"},
    23: {"win": "won the moments that decided fights", "loss": "won moments, lost the game"},
    24: {"win": "set the pace of the match", "loss": "set the pace, couldn’t close"},
    25: {"win": "forced the enemy to play around them", "loss": "forced respect without a win"},
    26: {"win": "built win conditions through pressure", "loss": "built win conditions that went unused"},
    27: {"win": "compounded advantage steadily", "loss": "compounded advantage in a loss"},
    28: {"win": "dictated the flow of the game", "loss": "dictated flow without a win"},
    29: {"win": "overwhelmed the enemy consistently", "loss": "overwhelmed the enemy but lost"},
    30: {"win": "was everywhere that mattered", "loss": "did everything they could"},
    31: {"win": "turned neutral moments in their favour", "loss": "did everything except win"},
    32: {"win": "forced mistakes without overreaching", "loss": "forced mistakes that weren’t punished"},
    33: {"win": "bent the game around their play", "loss": "bent the game, not the outcome"},
    34: {"win": "stacked advantages relentlessly", "loss": "stacked advantages in vain"},
    35: {"win": "played at an elite level", "loss": "played elite in defeat"},
    36: {"win": "won every moment that mattered", "loss": "won moments in a losing effort"},
    37: {"win": "played near-perfect Dota", "loss": "played near-perfect in a loss"},
    38: {"win": "delivered a masterclass performance", "loss": "delivered a masterclass in defeat"},
    39: {"win": "defined the match’s outcome", "loss": "defined the match but lost"},
    40: {"win": "was the central reason for the win", "loss": "was the central reason it was close"},
    41: {"win": "left the enemy without answers", "loss": "left the enemy scrambling, still lost"},
    42: {"win": "suffocated the enemy’s options", "loss": "suffocated options without closure"},
    43: {"win": "dictated terms all game", "loss": "dictated terms in a loss"},
    44: {"win": "could not be answered", "loss": "could not be answered, still fell"},
    45: {"win": "played at the ceiling of the match", "loss": "hit the ceiling in a loss"},
    46: {"win": "played tournament-grade Dota", "loss": "played tournament-grade in defeat"},
    47: {"win": "hard-carried the match", "loss": "hard-carried without reward"},
    48: {"win": "the match revolved around them", "loss": "the match revolved around them and collapsed anyway"},
    49: {"win": "delivered a legendary carry performance", "loss": "delivered a legendary carry in a loss"},
    50: {"win": "played a godlike game", "loss": "played godlike and still lost"},
    51: {"win": "put up an all-time performance", "loss": "put up an all-time performance in defeat"},
    52: {"win": "decided the match almost single-handedly", "loss": "played out of their mind but couldn’t save it"},
}
